### ISSUE TITLE
Error when connecting to database

### ISSUE THREAD

**Issue by dalareo** [keithyong/pyramus#1]
I get:

```
Unhandled rejection error: password authentication failed for user "usuario"
at Connection.parseE (/home/usuario/Software/news-community/pyramus/node_modules/pg/lib/connection.js:539:11)
at Connection.parseMessage (/home/usuario/Software/news-community/pyramus/node_modules/pg/lib/connection.js:366:17)
at Socket.<anonymous> (/home/usuario/Software/news-community/pyramus/node_modules/pg/lib/connection.js:105:22)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at Socket.Readable.push (_stream_readable.js:110:10)
at TCP.onread (net.js:523:20)
```

**Comment by paoyong** [comment]
Weird, I had no issues logging in. Could you try again, with a new account?
